services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: links_analyzer_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped


  worker:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: links_analyzer_worker
      command: celery -A app.worker.celery_app:celery_app worker --loglevel=info
      env_file:
        - .env
      volumes:
        - .:/app
      depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_healthy
      restart: unless-stopped


  postgres:
    image: postgres:16
    container_name: links_analyzer_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - links_analyzer_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: unless-stopped


  redis:
    image: redis:7
    container_name: links_analyzer_redis
    ports:
      - "6379:6379"
    volumes:
      - links_analyzer_redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped


volumes:
  links_analyzer_pg_data:
  links_analyzer_redis_data:
