"""create analysis tables

Revision ID: c9723af6cd7e
Revises: 
Create Date: 2026-07-21 19:12:01.412632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9723af6cd7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('total_urls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed_urls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'done', 'failed')", name='ch_status_task'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_tasks_status'), 'analysis_tasks', ['status'], unique=False)
    op.create_table('website_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('links_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('images_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('html_size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cached', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_result_task_id_url', 'website_result', ['task_id', 'url'], unique=False)
    op.create_index(op.f('ix_website_result_task_id'), 'website_result', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_result_task_id'), table_name='website_result')
    op.drop_index('idx_result_task_id_url', table_name='website_result')
    op.drop_table('website_result')
    op.drop_index(op.f('ix_analysis_tasks_status'), table_name='analysis_tasks')
    op.drop_table('analysis_tasks')
    # ### end Alembic commands ###
