"""Add uniq constraint to WebsiteResult

Revision ID: dac777623f5d
Revises: c9723af6cd7e
Create Date: 2026-07-28 19:25:24.149986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac777623f5d'
down_revision: Union[str, Sequence[str], None] = 'c9723af6cd7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_result_task_id_url'), table_name='website_result')
    op.create_unique_constraint('uniq_task_id_url', 'website_result', ['task_id', 'url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_task_id_url', 'website_result', type_='unique')
    op.create_index(op.f('idx_result_task_id_url'), 'website_result', ['task_id', 'url'], unique=False)
    # ### end Alembic commands ###
